In [1]:
import numpy as np

In [2]:
np.zeros(4)

array([0., 0., 0., 0.])

In [3]:
np.ones(4)

array([1., 1., 1., 1.])

In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [8]:
lista1 = [1,2,3,4]
array1 = np.array(lista1)

In [9]:
array1

array([1, 2, 3, 4])

In [10]:
lista1

[1, 2, 3, 4]